#!/usr/bin/env python
# coding: utf-8

# In[ ]:


'Austrian Bundesliga',
'Belgian First Division A',
'Brazilian Série A',
'Champions League',
'Championship',
'Cymru Premier',
'Danish Superliga',
'Dutch Eredivisie',
'EFL Cup',
'EFL Trophy',
'Euro U21 Qualifying',
'Europa Conference League',
'Europa League',
'FA Cup Qualifying',
'Finnish Veikkausliiga',
'French Ligue 1',
'German Bundesliga',
'Greek Superleague',
'Highland League',
'International Friendlies',
'Irish Premier Division',
'Irish Premiership',
'Italian Serie A',
'League One',
'League Two',
'Lowland League',
'National League',
'National League North',
'National League South',
'Norwegian Eliteserien',
'Portuguese Primeira Liga',
'Premier League',
'Russian Premier League',
'Scottish Challenge Cup',
'Scottish Championship',
'Scottish Cup',
'Scottish Cup Qualifying',
'Scottish League Cup',
'Scottish League One',
'Scottish League Two',
'Scottish Premiership',
"Scottish Women's Premier League 1",
'Spanish La Liga',
'Swedish Allsvenskan',
'Swiss Super League',
"The FA Women's Championship",
"The FA Women's Super League",
'Turkish Super Lig',
'Under-21 Friendly',
'United States Major League Soccer',
'Welsh Cup',
'Welsh League Cup',
"Women's Champions League",
'FIFA World Cup',
'CONMEBOL Copa America'
